Initial optimisation functionality
aaf6aa/tin pull request #31
Opened 2022-04-15 18:15 UTC by jotslo

ASTs now automatically get optimised when compiling.

Example:
An AST derived from the following code...
```
i32 test = 5;
test = test + 1; //6

fn void unused_func
{
    test = 73;
    test = test - 1;
}

fn i32 main
{
    test = test + 1; //7

    if (true == true)
    {
        if (test < 1) //false
        {
            print "wrong";
        }
        else if ((test + 1) / 2 == 4) //true
        {
            print test; //7
        }
    }

    return 0;
}
```

will be optimised to...

```
fn i32 main
{
    {
        {
            // scopes remain in-case code relies on scope
            print 7;
        }
    }

    return 0;
}
```

Optimisations include:
- If/else/elseif statements with determinable values are replaced with their inner scopes where possible
- Unused variables/functions are removed from the AST
- Expressions containing determinable symbols/values are replaced with their result

I have tested all the edge cases that I could think of, and none of the unit tests appear to give incorrect ASTs, so hopefully this should be mergeable without any issues. Let me know if there are any issues though.

TODO:
- Functions, for loops and while loops declare variables as indeterminable after being called/used to prevent inaccurate optimisations. Will look at improving this functionality in the future.

2022-04-15 20:00 UTC, aaf6aa commented
I have a question, why'd you remove .gitignore?

2022-04-15 20:20 UTC, jotslo commented
> I have a question, why'd you remove .gitignore?

That’s my bad, I intended to have the pull request ignore the changes I made but accidentally removed the files - I’ve added them back to the branch

2022-04-15 20:23 UTC, aaf6aa commented
Alright, I'll continue my review. Though, if it is possible, could you revert the commits instead of adding the files back, doing this destroys the file history. If not I'll do it myself.

2022-04-15 20:25 UTC, jotslo commented
> Alright, I'll continue my review. Though, if it is possible, could you revert the commits instead of adding the files back, doing this destroys the file history. If not I'll do it myself.

If you’re looking through now and are happy to, please could you sort that then please? Otherwise, I can redo it in a few hours when I’ve got access to a PC - whichever is easiest

2022-04-15 22:21 UTC, aaf6aa requested changes
You should make sure that all files in `examples/` compile correctly with your changes as they are basically our baseline until automated testing is implemented and should not be broken by changes, ignore files in `units/` and the units you wrote here though, they're not required to be runnable.

Additionally, clean up the memory leaks I pointed out. Use `make memcheck` and `make memcheck_full` to see where leaks are happening; these commands can also point out what's causing segmentation faults if you are getting them.

Also merge main into this branch so your checks are relevant, there have been some changes to the makefile jsyk

2022-04-15 22:21 UTC, aaf6aa commented on .gitignore
> +txt.txt
Ignore these files with a wildcard, like "*.txt", instead of writing each filename individually

2022-04-15 22:21 UTC, aaf6aa commented on src/tin.c
> +	optimize(mod, mod->ast_root);
The code currently cannot compile some example files, such as examples/include.tin, and instead segfaults. Omitting the call to optimize results in it compiling successfully, so there must be an issue within the optimization code.

2022-04-15 22:21 UTC, aaf6aa commented on src/optimisation.c
> +        children = vector_copy(node->children);
Memory leak

2022-04-15 22:21 UTC, aaf6aa commented on src/optimisation.c
> +                ast_node* new_node = ast_new(AstIntegerLit);
Memory leak

2022-04-15 22:21 UTC, aaf6aa commented on src/optimisation.c
> +                ast_node* data_type_node = ast_new(AstDataType);
Memory leak

2022-04-15 22:21 UTC, aaf6aa commented on src/optimisation.c
> +    ast_node* new_node = ast_new(AstBoolLit);
Memory leak

2022-04-15 22:21 UTC, aaf6aa commented on src/optimisation.c
> +                data_type_node->value.dtype = data_type_new(
Memory leak

2022-04-15 23:43 UTC, aaf6aa commented on src/tin.c
> +#include "optimisation.h"
The main function is called `optimize`, check your s's and z's.

2022-04-28 23:51 UTC, aaf6aa approved these changes

2022-04-28 23:55 UTC, aaf6aa commented
well done, you've surprised me, i approve this PR

2022-04-28 23:59 UTC, XiiiC approved these changes
Looks good! great work!

2022-04-29 00:12 UTC, merged